### ISSUE TITLE
Installation fails on youtube-dl - Installation dependencies? 

### ISSUE THREAD

**Issue by faultfactory** [udacimak/udacimak#1]
Hello, 

I'm installing the most recent version of node an npm via these instructions: 
'https://websiteforstudents.com/install-the-latest-node-js-and-nmp-packages-on-ubuntu-16-04-18-04-lts/'

When i run 'npm install -g udacimak' I get the following error: 
'''
> youtube-dl@1.12.2 postinstall /usr/lib/node_modules/udacimak/node_modules/youtube-dl
> node ./scripts/download.js

/usr/lib/node_modules/udacimak/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/udacimak/node_modules/youtube-dl/bin'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/usr/lib/node_modules/udacimak/node_modules/mkdirp/index.js:71:13)
    at createBase (/usr/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:51:12)
    at downloader (/usr/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:64:5)
    at Object.<anonymous> (/usr/lib/node_modules/udacimak/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@1.12.2 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.12.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
'''

I'm new to node and npm but know linux and other languages pretty well. I'm clearly missing something here. 

Is there a specific way i need to install youtube-dl?  I'm on ubuntu 16.04

**Comment by faultfactory** [comment]
I created a new 18.04 vm and started clean. I ran into the same issues with clean installations of node.js and npm. 

I then found this page 
'https://docs.npmjs.com/getting-started/fixing-npm-permissions' 

The procedure there allowed me to install but still throws an npm update error at the end. I can live with this.

**Comment by udacimak** [comment]
Hi @faultfactory 

Could you please paste the _npm update error_ log here?

I have no access to Ubuntu at the moment so I can't try to replicate the issue yet. But searching around has led me to the same article regarding fixing npm permissions.

It looks like someone else' package had this problem before with `node-youtube-dl`: https://github.com/przemyslawpluta/node-youtube-dl/issues/93

**Comment by faultfactory** [comment]
It presents a box like this with uname being my user name. 

┌─────────────────────────────────  ────┐
│                 npm update check failed                                         │
│           Try running with sudo or get access                              │
│          to the local update config store via                                │
│ sudo chown -R $USER:$(id -gn $USER) /home/uname/.config │
└──────────────────────────────────────┘
I can execute it just find with sudo

**Comment by udacimak** [comment]
That's a Node warning but Udacimak should be working fine. Please open more issues if you see any errors. Thanks!

**Comment by faultfactory** [comment]
Yes, agreed, I should have clarified. Udacimak is running and scraping content just fine.

**Comment by TasneemOmara** [comment]
I had the same problem, installed node and npm through nvm, tried to install different versions of node and npm, the problem is still there with the same error

**Comment by udacimak** [comment]
@TasneemOmara  Please copy the error log to your message

**Comment by TasneemOmara** [comment]
/home/tsneemomara/.nvm/versions/node/v11.2.0/bin/udacimak -> /home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/lib/index.js

> youtube-dl@1.12.2 postinstall /home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/youtube-dl
> node ./scripts/download.js

/home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin'
    at Object.mkdirSync (fs.js:776:3)
    at Function.sync (/home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/mkdirp/index.js:71:13)
    at createBase (/home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:54:12)
    at downloader (/home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/youtube-dl/lib/downloader.js:67:5)
    at Object.<anonymous> (/home/tsneemomara/.nvm/versions/node/v11.2.0/lib/node_modules/udacimak/node_modules/youtube-dl/scripts/download.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtube-dl@1.12.2 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.12.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tsneemomara/.npm/_logs/2018-11-25T12_13_49_803Z-debug.log

**Comment by TasneemOmara** [comment]
It works! Thank you

**Comment by AnkS4** [comment]
Installation via yarn is working, but not directly by npm.

[Log Here](https://gist.github.com/AnkS4/8641b300ed525b7c671a115ab3e9fbe3)

**Comment by udacimak** [comment]
@AnkS4 Thanks for the log! This is an issue with `node-youtube-dl` package and I'm not planning to produce a fix for now.

**Comment by MohammedElsayedAhmed** [comment]
I have a pretty similar error, i have installed node and npm through nvm and also installed git. the problem is when i use  " npm install -g udacimak " command it gives me this error 


npm ERR! Linux 4.15.0-39-generic
npm ERR! argv "/home/mohammed/.nvm/v0.10.48/bin/node" "/home/mohammed/.nvm/v0.10.48/bin/npm" "install" "-g" "udacimak"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.12.2 postinstall: `node ./scripts/download.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the youtube-dl@1.12.2 postinstall script 'node ./scripts/download.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mohammed/npm-debug.log

**Comment by adarshaU** [comment]
This works for me.
sudo npm install -g udacimak --unsafe-perm=true --allow-root

**Comment by brtn86** [comment]
Hi, unfortunately I run into errors with both installation approaches mentioned here:

yarn global add udacimak
==>
yarn global v1.13.0
[1/4] Resolving packages...
? youtube-dl@github:przemyslawpluta/node-youtube-dl#3349cbb6e067b6c9e7605acfa4f9
warning udacimak > npm > npm-registry-fetch@1.1.1: this version has a breaking c
hange. use 1.1.0 or upgrade to latest
warning udacimak > npm > npm-registry-fetch > make-fetch-happen > socks-proxy-ag
ent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avo
id a serious bug with socket data flow and an import issue introduced in 2.1.0
error Couldn't find match for "3349cbb6e067b6c9e7605acfa4f9d1ccc895fb0c" in "ref
s/heads/master,refs/pull/10/head,refs/pull/10/merge,refs/pull/108/head,refs/pull
/113/head,refs/pull/118/head,refs/pull/118/merge,refs/pull/122/head,refs/pull/12
2/merge,refs/pull/129/head,refs/pull/130/head,refs/pull/135/head,refs/pull/136/h
ead,refs/pull/152/head,refs/pull/152/merge,refs/pull/153/head,refs/pull/155/head
,refs/pull/16/head,refs/pull/163/head,refs/pull/163/merge,refs/pull/164/head,ref
s/pull/164/merge,refs/pull/17/head,refs/pull/171/head,refs/pull/172/head,refs/pu
ll/174/head,refs/pull/18/head,refs/pull/185/head,refs/pull/185/merge,refs/pull/1
9/head,refs/pull/193/head,refs/pull/195/head,refs/pull/195/merge,refs/pull/196/h
ead,refs/pull/20/head,refs/pull/210/head,refs/pull/213/head,refs/pull/218/head,r
efs/pull/24/head,refs/pull/25/head,refs/pull/27/head,refs/pull/28/head,refs/pull
/29/head,refs/pull/29/merge,refs/pull/3/head,refs/pull/3/merge,refs/pull/33/head
,refs/pull/35/head,refs/pull/36/head,refs/pull/37/head,refs/pull/4/head,refs/pul
l/4/merge,refs/pull/41/head,refs/pull/42/head,refs/pull/44/head,refs/pull/45/hea
d,refs/pull/46/head,refs/pull/47/head,refs/pull/5/head,refs/pull/5/merge,refs/pu
ll/55/head,refs/pull/55/merge,refs/pull/56/head,refs/pull/59/head,refs/pull/59/m
erge,refs/pull/62/head,refs/pull/64/head,refs/pull/65/head,refs/pull/72/head,ref
s/pull/75/head,refs/pull/84/head,refs/pull/85/head,refs/pull/85/merge,refs/pull/
92/head,refs/pull/92/merge,refs/pull/95/head,refs/pull/95/merge,refs/tags/rm,ref
s/tags/v1.0.4,refs/tags/v1.1.0,refs/tags/v1.10.0,refs/tags/v1.10.1,refs/tags/v1.
10.2,refs/tags/v1.10.3,refs/tags/v1.10.4,refs/tags/v1.10.5,refs/tags/v1.11.0,ref
s/tags/v1.11.1,refs/tags/v1.12.1,refs/tags/v1.2.0,refs/tags/v1.2.1,refs/tags/v1.
2.10,refs/tags/v1.2.11,refs/tags/v1.2.12,refs/tags/v1.2.2,refs/tags/v1.2.3,refs/
tags/v1.2.4,refs/tags/v1.2.5,refs/tags/v1.2.6,refs/tags/v1.2.7,refs/tags/v1.2.8,
refs/tags/v1.2.9,refs/tags/v1.3.0,refs/tags/v1.3.1,refs/tags/v1.3.2,refs/tags/v1
.3.3,refs/tags/v1.3.4,refs/tags/v1.3.5,refs/tags/v1.3.6,refs/tags/v1.4.0,refs/ta
gs/v1.5.0,refs/tags/v1.5.1,refs/tags/v1.5.10,refs/tags/v1.5.11,refs/tags/v1.5.12
,refs/tags/v1.5.13,refs/tags/v1.5.14,refs/tags/v1.5.15,refs/tags/v1.5.16,refs/ta
gs/v1.5.2,refs/tags/v1.5.3,refs/tags/v1.5.4,refs/tags/v1.5.5,refs/tags/v1.5.6,re
fs/tags/v1.5.7,refs/tags/v1.5.8,refs/tags/v1.5.9,refs/tags/v1.6.0,refs/tags/v1.7
.0,refs/tags/v1.8.0,refs/tags/v1.9.0" for "https://github.com/przemyslawpluta/no
de-youtube-dl.git".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this c
ommand.

npm install -g udacimak --unsafe-perm=true --allow-root
==>
npm ERR! Error while executing:
npm ERR! C:\Program Files (x86)\Git\cmd\git.EXE ls-remote -h -t ssh://git@github
.com/przemyslawpluta/node-youtube-dl.git
npm ERR!
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.
113' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\burtelli\AppData\Roaming\npm-cache\_logs\2019-01-10T11_31_
16_182Z-debug.log

Any ideas? Thanks.

**Comment by oba2311** [comment]
`npm update -g udacimak` and then install solved it for me. G'luck!

**Comment by AnkS4** [comment]
Installation with npm works now:

```
$ npm list -g --depth=0 
/home/anks/.npm-global/lib
├── udacimak@1.4.0
└── youtube-dl@2.0.0
```

**Comment by udacimak** [comment]
Thanks, @AnkS4 
I've released `v1.4.1` that updates `youtube-dl`

**Comment by cipheraxat** [comment]
Hey @udacimak  help me remove this error



base) akshat@akshat-Inspiron-5570:~$ sudo udacimak login
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/bin/details'
    at Object.openSync (fs.js:443:3)
    at readFileSync (fs.js:343:35)
    at module.exports (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/get-binary.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/udacimak/node_modules/youtube-dl/lib/youtube-dl.js:18:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)

**Comment by sangxxh** [comment]
@cipheraxat Please open a new issue for your error
